### ISSUE TITLE
THREADS_PREFER_PTHREAD_FLAG

### ISSUE THREAD

**Issue by lukasm91** [abseil/googletest#1955]
https://github.com/google/googletest/blob/master/googletest/cmake/internal_utils.cmake#L59 

On this line we set `THREADS_PREFER_PTHREAD_FLAG` to ON. This may trigger strange behaviour and also errors in certain cases:

- If you link a CUDA-enabled language against a gtest on a machine where CMake detects `-pthread`, this will not compile because the flags is propagated to the CUDA target, but the flag is not recognized by nvcc. On this machine, we don't want the pthread flag.  This is probably not that important as this is a general CMake problem.
- If you do `find_package(Threads)` already before adding googletest, this will lead to strange behaviour: The first cmake pass will do the `find_package(Threads)` with the option disabled  (or whatever the user specified), the second cmake pass will add the flag and find `-pthread`.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
ping
