### ISSUE TITLE
How to uninstall googletest?

### ISSUE THREAD

**Issue by eyildiz-ugoe** [abseil/googletest#1962]
Googletest seems to be screwing my installation of [libgp](https://github.com/mblum/libgp) and I would like to remove Googletest once for all. 

I installed it via following the instructions so, how could I now remove it?

Thanks in advance.

**Comment by gennadiycivil** [comment]
@eyildiz-ugoe It would be helpful to see what exactly you did when you installed it.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
