### ISSUE TITLE
CODE coverage

### ISSUE THREAD

**Issue by satish413** [abseil/googletest#1968]
Does google c++ testing have code coverage facility interface.if so mention how in a detailed view

**Comment by gennadiycivil** [comment]
Please explain a bit more your question, not clear what you would like to know. Thank you

**Comment by satish413** [comment]
I am using Google test for c++ unit testing. How would I get code coverage using it

**Comment by gennadiycivil** [comment]
Googletest is just a C++ unit testing implementation.
For code coverage you will need to connect code coverage tools to your
repository.

**Comment by satish413** [comment]
How to port googlest library to my source code which is building perfectly using makefile

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
