### ISSUE TITLE
Fails to build with -Wsign-conversion

### ISSUE THREAD

**Issue by gagbo** [abseil/googletest#1994]
This is maybe linked to #730 

EDIT : I forgot to change `LANG` for the compilation output, hopefully it is still easy to understand, I can probably do another run if you need

## Issue
I cannot build a [simple project](https://framagit.org/gagbo/gtest_cmake_project/tree/2542b952a3bf46992219fce82385f1797681e4be) if I enable warnings for sign-conversions.

## Versions

- Fedora Linux (Rawhide)
- Googletest 8fbf9d16
- Cmake : `cmake.x86_64 3.12.2-1.fc30 @rawhide`
- gcc : `gcc.x86_64 8.2.1-5.fc30 @rawhide`

## Steps to reproduce : 

- Clone (recursively) https://framagit.org/gagbo/gtest_cmake_project/tree/2542b952a3bf46992219fce82385f1797681e4be (Specific commit left in the address here, but I'll leave master pointing there until this issue is solved)
- `mkdir build`
- `cd build`
- `cmake ..`
- `make`

## Expected results

- Project builds

## Actual results

Errors with sign-conversion warnings enabled : https://paste.fedoraproject.org/paste/xz02qkLBtqtnqrUZ7CaPDw

## Note
 
I did not do the full dichotomy yet, but just commenting my "basic" warning compilation flags [here](https://framagit.org/gagbo/gtest_cmake_project/blob/2542b952a3bf46992219fce82385f1797681e4be/CMakeLists.txt#L10) is enough to be able to build.

**Comment by gennadiycivil** [comment]
@gagbo thank you for this report. Note that googletest is not in position to support all compiler warnings. 
-Wsign-conversion is not something we support.  Was there a particular reason you want this warning on?

**Comment by gennadiycivil** [comment]
Note that we would consider a PR that can prove that it actually catches bugs. However we wont support this flag "in general"

**Comment by gagbo** [comment]
It was there just because it is one of the warnings I want to catch while developing.

Now that I think about it, the solution *should* be to set the flags only for the targets I want, instead of setting the flag as a global one. Should I do so, is there a particular set of flags I should set for gtest when I use it as a submodule for tests in a bigger project ?

As you can see from the repo I linked, this is really only a skeleton for me to learn and experiment with proper CMake configurations. I would like to reach the same level of integration as this [Travis/Catch2/FetchContent alternative skel](https://github.com/gagbo/catch2_cmake_project) I built : 

- I want to automatically pull/include the testing framework from the internet (in one case I tried FetchContent, in another git submodule)
- I am exclusively a **user** of the testing framework
- I want to have some CI support

**Comment by gennadiycivil** [comment]
* The experience with various compiler options led the team here to believe
that this particular warning is not super helpful and creates noise in
most cases. You did not specify WHY this one is "*one of the warnings I
want to catch while developing.*".
* You should be able to pull in latest googletest as you need.
